name: Збірка та публікація Docker-образу

on:
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Встановлення pnpm, залежностей і збірка проєкту
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Вхід у GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Збірка і публікація Docker-образу
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/danielpanchenko04/frontend:latest

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-web-app-lab-9
          images: ghcr.io/danielpanchenko04/frontend:latest

