name: Збірка та публікація Docker-образу

on:
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Встановлення pnpm, залежностей і збірка проєкту
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Вхід у GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Збірка і публікація Docker-образу
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
<<<<<<< HEAD
          tags: ghcr.io/${{ github.repository | toLowerCase() }}
=======
          tags: ghcr.io/danielpanchenko04/backend
>>>>>>> 45579092d8467b6d5b0ba749560c6658c2a51bb4
